export const optionsColor = "rgba(31, 36, 41, 0.05)";

type Question = {
  question: string;
  number: number;
  section: number;
  a: string;
  b: string;
  containerColor: string;
  gradientColorStart: string;
  gradientColorEnd: string;
};

export const questions: Array<Array<Question>> = [
  [
    {
      question: "I understand an algorithm better After I:",
      number: 1,
      section: 1,
      a: "Try that algorithm on different examples 💡",
      b: "Think about algorithm's overall processes 🌐",
      containerColor: "#E9E6F9",
      gradientColorStart: "#9D86FB",
      gradientColorEnd: "#DBD2FF",
    },
    {
      question: "I would try to learn algorithms by:",
      number: 2,
      section: 1,
      a: "Learning it through more examples by changing the values",
      b: "Learning on some more cases through changing the scenarios",
      containerColor: "#E8E9F8",
      gradientColorStart: "#8086FF",
      gradientColorEnd: "#D8DAFD",
    },
    {
      question: "When I think about yesterday's Algorithms class:",
      number: 3,
      section: 1,
      a: "I got a whole picture of Algorithm in my mind 🖼️",
      b: "I only got words Of Algorithm like Text 💬",
      containerColor: "#E7ECF8",
      gradientColorStart: "#79A7FF",
      gradientColorEnd: "#D5E2FB",
    },
    {
      question: "When I learn about Algorithms:",
      number: 4,
      section: 1,
      a: "I understand that this is a Bubble sort but I'm unable to understand its entire working 📉",
      b: "I understand its entire working but I am unable to understand that this is a Bubble Sort 🔵",
      containerColor: "#E6EFF7",
      gradientColorStart: "#68C4FE",
      gradientColorEnd: "#D2EAF9",
    },
    {
      question: "When I am learning new algorithms:",
      number: 5,
      section: 1,
      a: "I can talk about it with my colleagues/friends",
      b: "I can think about that algorithms 💭",
      containerColor: "#E5F2F7",
      gradientColorStart: "#7FE9F9",
      gradientColorEnd: "#CFF2F7",
    },
    {
      question: "If I were the teacher of Algorithms, then:",
      number: 6,
      section: 1,
      a: "I would love to deal with facts and real life situations 📢",
      b: "I would love to deal with only ideas and theories 📚",
      containerColor: "#E5FBF6",
      gradientColorStart: "#82F6F6",
      gradientColorEnd: "#C7F2F2",
    },
    {
      question: "I acquire new information about algorithms:",
      number: 7,
      section: 1,
      a: "By watching Multimedia, videos, and animations 📺",
      b: "By reading text and listening verbally 📖",
      containerColor: "#E5FBF3",
      gradientColorStart: "#78F9DF",
      gradientColorEnd: "#C4F2E9",
    },
    {
      question: "I understand the algorithm through:",
      number: 8,
      section: 1,
      a: "Discussing the parts of the algorithm and then concluding it with the whole structure (For Example in case of Divide and Conquer Approach in Merge Sort, first discuss the divide part and then the conquer part and then the whole algorithm of merge sort) ➗",
      b: "Discussing the whole algorithm and then the individual parts (For Example in case of Divide and Conquer Approach in Merge Sort, first discuss the merge sort completely then discuss divide and conquer part) 🧩",
      containerColor: "#E5FBF0",
      gradientColorStart: "#C1F2E0",
      gradientColorEnd: "#C1F2E0",
    },
    {
      question: "During the group study on algorithms:",
      number: 9,
      section: 1,
      a: "I will jump in and contribute ideas 💡 ",
      b: "I sit back and only listen 👂🏼",
      containerColor: "#E5FBED",
      gradientColorStart: "#70FAB2",
      gradientColorEnd: "#BEF2D7",
    },
    {
      question: "In learning algorithms I find it easier:",
      number: 10,
      section: 1,
      a: "To learn through facts 🌐",
      b: "To learn through Concepts 💭",
      containerColor: "#E5FBEB",
      gradientColorStart: "#78FCA3",
      gradientColorEnd: "#BBF5CE",
    },
    {
      question: "While reading books with figures:",
      number: 11,
      section: 1,
      a: "Visual aids such as charts and pictures are beneficial for learning 📊",
      b: "Text based materials are helpful for learning ✍🏻",
      containerColor: "#E5FBEA",
      gradientColorStart: "#7BFE86",
      gradientColorEnd: "#BBF5C0",
    },
  ],
  [
    {
      question: "When I solve some mathematical problems i usually solve it",
      number: 1,
      section: 2,
      a: "Step by Step 👣",
      b: "First see the solution and then figure out the step to get to the answer 💡",
      containerColor: "#E6FBE8",
      gradientColorStart: "#7FFC76",
      gradientColorEnd: "#BDF4B9",
    },
    {
      question: "In class, do you easily socialize with classmates?:",
      number: 2,
      section: 2,
      a: "I easily socialize with classmates 🗣",
      b: "I do not easily socialize classmates 🙅🏻‍",
      containerColor: "#E7FBE7",
      gradientColorStart: "#86F06B",
      gradientColorEnd: "#BFF3B2",
    },
    {
      question:
        "When I am reading the reference or text book I prefer those books that teaches me:",
      number: 3,
      section: 2,
      a: "Something that teaches me new facts or tells me how to do something 🧠",
      b: "Something that gives me new ideas to think about 💡",
      containerColor: "#E8FBE6",
      gradientColorStart: "#98F06E",
      gradientColorEnd: "#C2F2AB",
    },
    {
      question: "When studying computer algorithms, I prefer instructors who:",
      number: 4,
      section: 2,
      a: "Utilize diagrams to illustrate concepts ✏",
      b: "Provide comprehensive explanations of the topic 📝",
      containerColor: "#E9FBE5",
      gradientColorStart: "#9BF25D",
      gradientColorEnd: "#C4F1A4",
    },
    {
      question: "When I'm analyzing a story or a novel:",
      number: 5,
      section: 2,
      a: "I think of the incidents and try to put them together to figure out the theme 🤔",
      b: "I just know what the themes are when I finish reading and then I have to go back and find the incidents that demonstrate them 🔄",
      containerColor: "#EAFBE5",
      gradientColorStart: "#A3F85C",
      gradientColorEnd: "#C4F898",
    },
    {
      question: "When I start a homework problem, I am more likely to:",
      number: 6,
      section: 2,
      a: "Start working on the solution immediately 🚀",
      b: "Try to fully understand the problem first 🧠",
      containerColor: "#ECFBE5",
      gradientColorStart: "#B8FA65",
      gradientColorEnd: "#D0F89D",
    },
    {
      question: "Which type of algorithmic concepts do you prefer?:",
      number: 7,
      section: 2,
      a: "I prefer concepts backed by concrete evidence in the form of proofs 🔍",
      b: "I prefer concepts based solely on theoretical explanations basis on hypothesis 🤓",
      containerColor: "#EEFBE5",
      gradientColorStart: "#D0FC76",
      gradientColorEnd: "#DCF8A2",
    },
    {
      question: "I remember concepts best:",
      number: 8,
      section: 2,
      a: "After seeing the simulations 👀",
      b: "After hearing the explanation 👂🏻",
      containerColor: "#F0FBE5",
      gradientColorStart: "#E0F97D",
      gradientColorEnd: "#E8F8A7",
    },
    {
      question: "It is more important to me that an instructor:",
      number: 9,
      section: 2,
      a: "Teaches the algorithm in clear sequential steps 📚",
      b: "Give the picture of the overall problem and relate the material with other subjects 🖼",
      containerColor: "#F2FBE5",
      gradientColorStart: "#F7FE80",
      gradientColorEnd: "#F4F8AC",
    },
    {
      question: "When studying computer algorithms, I prefer to:",
      number: 10,
      section: 2,
      a: "Study within a group 👥",
      b: "Study individually, without a group 🙋",
      containerColor: "#F7FBE5",
      gradientColorStart: "#FBFD86",
      gradientColorEnd: "#F8F9B4",
    },
    {
      question: "I am more likely to be considered:",
      number: 11,
      section: 2,
      a: "Careful about presenting the details of my work 🧐",
      b: "Creative (think out of the box) on my work by giving creative solutions 🎨",
      containerColor: "#F8FAE5",
      gradientColorStart: "#FDF98C",
      gradientColorEnd: "#FCFABD",
    },
  ],
  [
    {
      question: "When I get directions to a new place, I prefer:",
      number: 1,
      section: 3,
      a: "A map 🗺",
      b: "Written directions ➡️",
      containerColor: "#F9F9E5",
      gradientColorStart: "#FBF08D",
      gradientColorEnd: "#FCF6BD",
    },
    {
      question: "How can I effectively learn?",
      number: 2,
      section: 3,
      a: "Regular pace and rigorous practice that lead to understanding 🔄",
      b: "Initially confusion may prevail, but sudden clarity often occurs when engaging with the material ❓",
      containerColor: "#FAF8E5",
      gradientColorStart: "#FFEC86",
      gradientColorEnd: "#FCF2BD",
    },
    {
      question:
        "When approaching a problem, which method do you prefer to employ first?:",
      number: 3,
      section: 3,
      a: "Try things out 🧪",
      b: "Engaging in planning the solution by how to do it 📝",
      containerColor: "#FBF6E5",
      gradientColorStart: "#F0D778",
      gradientColorEnd: "#FCEFBD",
    },
    {
      question: "When I am reading for enjoyment, I like writers to:",
      number: 4,
      section: 3,
      a: "Clearly say what they mean 🗨",
      b: "Say things in creative, interesting ways 🎭",
      containerColor: "#FBF3E5",
      gradientColorStart: "#F5DA91",
      gradientColorEnd: "#FCEBBD",
    },
    {
      question:
        "When I encounter a diagram or sketch related to computer algorithms, I tend to remember:",
      number: 5,
      section: 3,
      a: "The visual representation of the algorithm 📜️ ",
      b: "The verbal explanation provided by the instructor regarding the algorithm 🗣️",
      containerColor: "#FBF0E5",
      gradientColorStart: "#F9CE91",
      gradientColorEnd: "#FCE2BD",
    },
    {
      question: "When approaching a complex algorithm, my tendency is to:",
      number: 6,
      section: 3,
      a: "Focus on the details and may overlook the underlying logic 🔍",
      b: "Prioritize grasping the fundamental concept before going into the algorithm's details 👉",
      containerColor: "#FBEDE5",
      gradientColorStart: "#F6B37F",
      gradientColorEnd: "#FDD9BD",
    },
    {
      question: "I can easily recall specific types of information:",
      number: 7,
      section: 3,
      a: "Procedures I've executed 🛠️",
      b: "Concepts I've extensively studied 📚",
      containerColor: "#FBEAE5",
      gradientColorStart: "#FDAC8A",
      gradientColorEnd: "#FED0BD",
    },
    {
      question: "When I have solved the problem:",
      number: 8,
      section: 3,
      a: "I prefer to master one way of doing it 🎯",
      b: "I prefer to come up with new way of doing it 💡",
      containerColor: "#FBE7E5",
      gradientColorStart: "#FEA393",
      gradientColorEnd: "#FFC7BD",
    },
    {
      question: "When someone is showing me data, I prefer:",
      number: 9,
      section: 3,
      a: "Charts and graphs 📊",
      b: "Text summarizing the results 📝",
      containerColor: "#FBE6E5",
      gradientColorStart: "#FD8B8B",
      gradientColorEnd: "#FFBEBE",
    },
    {
      question: "When working on implementing algorithms, I am more likely to:",
      number: 10,
      section: 3,
      a: "Begin coding the algorithm and proceed linearly until completion 👍",
      b: "Begin coding the algorithm in different segments, then integrate them together at the end 🗂️",
      containerColor: "#FBE5E5",
      gradientColorStart: "#FC837E",
      gradientColorEnd: "#FFB8B5",
    },
    {
      question: "When approaching a collaborative algorithm development task, I prefer:",
      number: 11,
      section: 3,
      a: "Conducting a 'Group Brainstorming' session, allowing everyone to contribute ideas collaboratively 👥",
      b: "Individually brainstorming algorithmic solutions, then convening as a group to compare and refine the ideas 💻",
      containerColor: "#FBE5E8",
      gradientColorStart: "#FF8E8E",
      gradientColorEnd: "#FFB1B1",
    },
  ],
  [
    {
      question: "I consider it higher praise to call someone:",
      number: 1,
      section: 4,
      a: "Sensible: One who prefers practical, factual, and concrete information that doesn't defy reality 💭",
      b: "Imaginative: One who prefers creative, abstract, and theoretical ideas beyond immediate reality 🔮",
      containerColor: "#FBE5EB",
      gradientColorStart: "#F5919E",
      gradientColorEnd: "#FFB7C0",
    },
    {
      question: "When I meet people at a party, I am more likely to remember:",
      number: 2,
      section: 4,
      a: "What they looked like 🧑🏻",
      b: "What they said about themselves 🗨",
      containerColor: "#FBE5EE",
      gradientColorStart: "#FF88A8",
      gradientColorEnd: "#FFBDCF",
    },
    {
      question: "When I am learning a new subject, I prefer to:",
      number: 3,
      section: 4,
      a: "Stay focused on that subject, learning as much about it as I can 👀",
      b: "Try to make connections between that subject and related subjects 🌐",
      containerColor: "#FBE5F1",
      gradientColorStart: "#FFADD2",
      gradientColorEnd: "#FFC3DE",
    },
    {
      question: "I am more likely to be considered:",
      number: 4,
      section: 4,
      a: "Outgoing: One who tends to be expressive, social, and energized by interacting with others 🤝",
      b: "Reserved: One who tends to be quiet, reflective, and prefers solitary or small-group settings 🤫",
      containerColor: "#FBE5F4",
      gradientColorStart: "#FDA8E0",
      gradientColorEnd: "#FFC9ED",
    },
    {
      question: "Which type of courses do you favor?:",
      number: 5,
      section: 4,
      a: "Concrete facts and real-world data 📁",
      b: "Abstract concepts and theoretical frameworks 🤔",
      containerColor: "#F7E5F5",
      gradientColorStart: "#EDB4FC",
      gradientColorEnd: "#F7D8FF",
    },
    {
      question: "For entertainment, I prefer to:",
      number: 6,
      section: 4,
      a: "I use multimedia technology for entertainment 🎮",
      b: "I read books for entertainment 📚",
      containerColor: "#F3E5F6",
      gradientColorStart: "#E2B6FF",
      gradientColorEnd: "#EED4FF",
    },
    {
      question:
        "Some teachers start their lectures with an outline of what they will cover. Such outlines are:",
      number: 7,
      section: 4,
      a: "Somewhat helpful to me 🤔",
      b: "Very helpful to me 😊",
      containerColor: "#EFE5F7",
      gradientColorStart: "#CDAAFA",
      gradientColorEnd: "#E5D0FF",
    },
    {
      question:
        "The idea of doing homework in groups, with one grade for the entire group:",
      number: 8,
      section: 4,
      a: "Appeals to me 😊",
      b: "Does not appeal to me 😕",
      containerColor: "#EBE5F8",
      gradientColorStart: "#CDB6FF",
      gradientColorEnd: "#DCCCFF",
    },
    {
      question: " When I am doing long calculations:",
      number: 9,
      section: 4,
      a: "I tend to repeat all my steps and check my work carefully ✅",
      b: "I find checking my work tiresome and have to force myself to do it 😩",
      containerColor: "#E8E5F9",
      gradientColorStart: "#AF9CFA",
      gradientColorEnd: "#D3C8FF",
    },
    {
      question: "I tend to picture places I have been:",
      number: 10,
      section: 4,
      a: "Easily and fairly accurately 📍",
      b: "With difficulty and without much detail",
      containerColor: "#E5E5FB",
      gradientColorStart: "#A59BFF",
      gradientColorEnd: "#CAC4FF",
    },
    {
      question: "When solving problems in a group, I would be more likely to:",
      number: 11,
      section: 4,
      a: "Think of the steps in the solutions process ⚙️",
      b: "Think of possible consequences or applications of the solution in a wide range of areas ⚖️",
      containerColor: "#E5E5FB",
      gradientColorStart: "#9798F8",
      gradientColorEnd: "#BCBDFF",
    },
  ],
];
